[package]
name = "type_defender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
strum = { version = "0.24.1", features = ["derive", "strum_macros"] }
strum_macros = "0.24.3"
termion = "1.5"
tui = { version = "0.19", default-features = false, features = ['termion'] }
tui-textarea = {version = "0.2.0", default-features = false, features = ['termion']}
